// Generated by https://quicktype.io

export interface Cliente {
    id:             number;
    nombres:        string;
    apellidos:      string;
    identificacion: string;
    telefono:       string;
    email:          string;
    direccion:      string;
    created_at:     Date;
    updated_at:     Date;
    deleted_at:     null;
}
